config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :meetings
  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'welcome', to: 'welcome#index'

  get 'volunteers/propose', to: 'volunteers#propose'

  resources :volunteers, except: [:index, :edit]

  root to: 'pages#home'

  get 'volunteers/propose', to: 'volunteers#propose'

  get '/contact', to: 'pages#contact'

  get '/news', to: 'pages#news'

  get '/about', to: 'about#who'

  get '/quickstart', to: 'pages#quickstart'

  #about
  get '/about/conduct', to: 'about#conduct'

  get '/about/diversity', to: 'about#diversity'

  get '/about/press', to: 'about#press'

  get '/about/principals', to: 'about#principals'

  get '/about/projects', to: 'about#projects'

  # get '/about/vision', to: 'about#vision'

  get '/about/what', to: 'about#what'

  #get '/projects', to: 'projects#show', as: 'projects_show'

end

app/models/meeting.rb
class Meeting < ApplicationRecord
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  access all: [:show], user: [:show], site_admin: :all
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:title, :subtitle, :location, :eventstart, :timeofevent, :url, :body)
    end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<%= form_with(model: meeting, local: true) do |form| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :meeting_title, class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle, id: :meeting_subtitle, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :location %>
    <%= form.text_area :location, id: :meeting_location, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :eventstart %>
    <%= form.datetime_select :eventstart, id: :meeting_eventstart, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :timeofevent %>
    <%= form.text_field :timeofevent, id: :meeting_timeofevent, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :url %>
    <%= form.text_area :url, id: :meeting_url, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, id: :meeting_body, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :googlemapurl %>
    <%= form.text_area :body, id: :meeting_googlemapurl, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<div class="container col-md-6 offset-md-3 topper">
<h1>Editing Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>
</div>

app/views/meetings/index.html.erb
<div class="container col-md-6 offset-md-3 topper">
<p id="notice"><%= notice %></p>

<h1>Meetings</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Subtitle</th>
      <th>Location</th>
      <th>Eventstart</th>
      <th>Timeofevent</th>
      <th>Url</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meetings.each do |meeting| %>
      <tr>
        <td><%= meeting.title %></td>
        <td><%= meeting.subtitle %></td>
        <td><%= meeting.location %></td>
        <td><%= meeting.eventstart %></td>
        <td><%= meeting.timeofevent %></td>
        <td><%= meeting.url %></td>
        <td><%= meeting.body %></td>
        <td><%= link_to 'Show', meeting %></td>
        <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
        <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meeting', new_meeting_path %>
</div>

app/views/meetings/new.html.erb
<div class="container col-md-6 offset-md-3 topper">
  <h1>Create New Meeting</h1>

  <%= render 'form', meeting: @meeting %>

  <%= link_to 'Back', meetings_path %>
</div>

app/views/meetings/show.html.erb
<div class="container col-md-6 offset-md-3 topper">
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @meeting.title %>
</p>

<p>
  <strong>Subtitle:</strong>
  <%= @meeting.subtitle %>
</p>

<p>
  <strong>Location:</strong>
  <%= @meeting.location %>
</p>

<p>
  <strong>Eventstart:</strong>
  <%= @meeting.eventstart %>
</p>

<p>
  <strong>Timeofevent:</strong>
  <%= @meeting.timeofevent %>
</p>

<p>
  <strong>Url:</strong>
  <%= @meeting.url %>
</p>

<p>
  <strong>Body:</strong>
  <%= @meeting.body %>
</p>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>
</div>