config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :meetings
  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'welcome', to: 'welcome#index'

  get 'volunteers/propose', to: 'volunteers#propose'

  resources :volunteers, except: [:index, :edit]

  root to: 'pages#home'

  get 'volunteers/propose', to: 'volunteers#propose'

  get '/contact', to: 'pages#contact'

  get '/news', to: 'pages#news'

  get '/about', to: 'about#who'

  get '/quickstart', to: 'pages#quickstart'

  #about
  get '/about/conduct', to: 'about#conduct'

  get '/about/diversity', to: 'about#diversity'

  get '/about/press', to: 'about#press'

  get '/about/principals', to: 'about#principals'

  get '/about/projects', to: 'about#projects'

  # get '/about/vision', to: 'about#vision'

  get '/about/what', to: 'about#what'

  #get '/projects', to: 'projects#show', as: 'projects_show'

end

app/views/pages/about.html.erb
<h1>Pages#about</h1>

app/views/pages/contact.html.erb
<div class="container col-md-8 offset-md-2 topper" style="margin-top: 60px;">
  <div class="container">
    <h1>Contact Us</h1>
    <ul>
      <li>
        <%= mail_to 'hugh@codeforpdx.org', 'Email' %>
      </li>
      <li>
        <%= link_to 'Twitter', 'https://twitter.com/codeforpdx', target: '_blank' %>
      </li>
      <li>
        <%= link_to 'Meetup.com', 'https://www.meetup.com/Code-for-PDX/', target: '_blank' %>
      </li>
      <li>
        <%= link_to 'Slack', 'https://codeforpdx.slack.com', target: '_blank' %>
      </li>
    </ul>
  </div>
</div>

app/views/pages/home.html.erb
<div id="main_featurette">
  <div id="titlecontainer">
    <h1>
       <strong><span>Code </span></strong>
       <span><em>for</em></span>
       <strong>
         <span id="pdx"> PDX </span>
       </strong>
    </h1>
    <p>
     As a <a href="http://www.codeforamerica.org" target="_blank"> Code for America Brigade </a>,
      we're part of a national network of civic-minded volunteers
      who contribute their skills toward using the web
      as a platform for local government and community service.
    </p>
  </div>
</div>

<div class="container">
  <br>
  <div class="row">
    <div class="col-md-8" style="color:black;">
        <% if @meeting %>
          <h1> Next Meeting: <%= @meeting.title %> </h1>
          <h2>Our Next meeting is <%= @meeting.eventstart.to_time.strftime('%a %b %d') %> at, <%= @meeting.eventstart.to_time.strftime('%H:%M:') %> </h2>
          <h2 class=><%= @meeting.location %> </h2>
          <p> <%= @meeting.body %> </p>
            <%= link_to  @meeting.url, target: "_blank" do  %>
              <div class="button" id="meetupbutton">
                <h5>RSVP NOW!</h5>
            </div>
          <% end %>
        </div>

        <div class="col-md-2">
          <iframe src= '<%= @meeting.googlemapurl %>'
                  width="400"
                  height="350"
                  frameborder="0"
                  style="border:0"
                  allowfullscreen>
          </iframe>
        </div>

      <% else %>
        <div class="row">
          <div class="col-lg-12">
              <h1 class="text_color"> Next Meeting: To Be Announced </h1>
              <h2 class=>Biweekly Hackathons: TBA </h2>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>


<hr>
<div class="sectionheader">
  <h1>Check Out Our Current Projects!</h1>
</div>
<div id="projectcontainer">


  <% @projects.each do |project| %>
    <div class="projects" style="background: <%= project.color %>;">
      <%= link_to "/projects/#{project.id}" do %>
        <div style="color: white;">
          <%= image_tag project.img, alt: project.title, margin: "20px" %>
        </div>
        <div style="color: white; text-align: left;">
          <h3> <%= project.title %> </h3>
          <p> <%= markdown project.text %> </p>
        </div>
      <% end %>
    </div>
    <% end %>
</div>

<hr>

<div class="featurecontainer background_white" style="min-height: 500px; padding: 40px;">
    <div class="sectionheader">
      <h1>Our Partners</h1>
    </div>

  <div class="partner grow">
    <%= link_to "https://www.freshconsulting.com/", target: "_blank" do %>
      <%= image_tag "fresh_regular_logo.png", alt: "Fresh Consulting", width: "450px", height:"200px;", margin: "20px"%>
    <% end %>
  </div>

  <div class="partner grow">
  <%= link_to "https://www.alchemycodelab.com/", target: "_blank" do %>
    <%= image_tag "alchemy.png", alt: "Alchemy Code Lab", width: "450px", height:"450px;", margin: "20px"%>
  <% end %>
</div>

<div class="partner grow">
<%= link_to "http://www.pizzajerkpdx.com/", target: "_blank" do %>
  <%= image_tag "pizzajerk.jpg", alt: "Pizza Jerk", width: "450px", height:"450px;", margin: "20px"%>
<% end %>
</div>

<div class="partner grow">
<%= link_to "https://xray.fm/", target: "_blank" do %>
  <%= image_tag "xray.png", alt: "XRAY FM", width: "450px", height:"250px;", margin: "20px"%>
<% end %>
</div>

  <div class="partner grow">
    <%= link_to "https://thecommonslawcenter.org/", target: "_blank" do %>
      <%= image_tag "commonslaw.png", alt: "Commons Law Center", width: "400px", height:"150px;", margin:"20px;"%>
    <% end %>
  </div>

</div>

<div class="featurecontainer background_darkblue">
  <div class="contact spaced text_white"  style="margin:20px 80px;">
    <br>
    <div class="text_white">
      <h1>Get In Touch:</h1>
    </div>
    <p>
      <i class="far fa-check-square text_greenblue "></i>
      Get started easily with our
      <%= link_to 'Quick Start Guide', quickstart_path, class: "text_greenblue" %>.
    </p>
    <p>
      <i class="fab fa-twitter-square text_greenblue"></i>
      Keep up with us on
      <%= link_to 'Twitter', 'https://twitter.com/codeforpdx', target: '_blank', class: "text_greenblue" %>
    </p>
    <p>
      <i class="fab fa-github-square text_greenblue"></i>
      Fork and modify our projects on
      <%= link_to 'Github', 'https://github.com/codeforpdx', target: '_blank', class: "text_greenblue"  %>.
    </p>
    <p>
      <i class="fab fa-slack text_greenblue"></i>
      Join the discussion! Chat with us on
      <%= link_to 'Slack', 'https://codeforpdx.slack.com/', target: '_blank', class: "text_greenblue" %>.
    </p>
    <p>
      <i class="fab fa-meetup text_greenblue"></i>
      Come to a meetup! Join us on
      <%= link_to 'Meetup.com', 'https://www.meetup.com/Code-for-PDX/', target: '_blank', class: "text_greenblue" %>
      for the updates on when and where we're meeting.
    </p>
  </div>
  <br>
</div>
<hr>
<div class="featurecontainer">
    <div class="sectionheader" style="padding: 10px 20px;">
      <h2> Support Code for PDX </h2>
    </div>
    <div style="padding: 60px;">
      <p>
        Our Supporters.
        We rely on the help of financial, in-kind supporters and government partners to sustain our efforts tactically and financially.
        While Code for America subsidizes our operating costs,
        if Code for PDX is to continue its mission we will soon need the financial support of local sponsors,
        By supporting Code for PDX with a tax-deductible contribution, your organization will receive recognition at our events and through our many communications channels.
        Funds go directly toward web hosting, meeting space, and food and beverages for our awesome volunteers.
      </p>
    </div>
    <div style="text-align: center;">
      <%= link_to "Donate Today!", "https://secure.codeforamerica.org/page/contribute/default?brigade=Code%20for%20PDX", class: "button" %>
    </div>
  </div>




<!-- /END THE FEATURETTES -->
<!--
<img class="featurette-image img-fluid mx-auto" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
-->

app/views/pages/news.html.erb
<div class="container col-md-8 offset-md-2 topper">
  <div class="container">
    <h1>Pages#news</h1>
  </div>
</div>

app/views/pages/quickstart.html.erb
<div class="container col-md-8 offset-md-2 col-xl-6 offset-xl-3 topper" style="margin-top: 60px;">
  <div class="container">
    <h1>Get Started Working With Code for PDX</h1>
    <h3><em>Building a better community is up to all of us</em></h3>

    <p>
      We're not just about building software! No matter what your skill set,
      we'd love to have you on board. Improving the community requires all types.
    </p>
    <ul>
      <li>
        <p>
        <strong>Subject-Matter Experts</strong><br>
        People building technological solutions are usually not experts in the
        field. If your technical expertise is a match for one of our projects,
        excellent! If not, we want to hear from you. Our developers can still use
        your guidance.
        </p>
      </li>
      <li>
        <p>
        <strong>Project Managers</strong><br>
        All important projects need someone to plan, set the course, and clear
        the roadblocks. If you have experience in tackling the big picture and
        predicting problems before they arise, we'd love to hear from you.
        </p>
      </li>
      <li>
        <p>
        <strong>Designers</strong><br>
        Good design guides every-day decisions, from the most impactful to the
        most mundane. If you know how to package information for maximum impact,
        we need you at Code for PDX.
        </p>
      </li>
      <li>
        <p>
        <strong>Advocates and Evangelists</strong><br>
        For our efforts to have a real impact, our projects need visibility -
        both to those who will benefit, and to those who can recommend our work.
        People with the gift for spreading the word are invaluable to what we do.
        </p>
      </li>
      <li>
        <p>
        <strong>Coders</strong><br>
        Most of our projects will involve creating technical solutions to improve
        people's lives. Come make an impact, while learning new skills along the
        way.
        </p>
      </li>
      <li>
        <p>
        <strong>Governments and Non-Profits</strong><br>
        Those with a strong overview of what our community needs are best placed
        to help stewart our projects as they evolve. If you work with a local
        government or organization focused on the common good, we want to hear
        from you.
        </p>
      </li>
    </ul>

    <p>
      As we get going, you'll be able to see what we're up to on the
      <%= link_to 'projects page', about_projects_path %>.
      Don't hesitate to
      <%= mail_to 'hugh@codeforpdx.org', 'send an email' %> asking how you
      can get involved, even if you don't see yourself in the list above.
    </p>

    <h1>Come Talk To Us</h1>
    <p>
      If you just want to get a feel for what's happening, join us on
      <%= link_to 'Slack', 'https://codeforpdx.slack.com', target: '_blank' %>
      and say hi on the #citizen-participation channel, or contact us on
      <%= link_to 'Twitter', 'https://twitter.com/codeforpdx', target: '_blank' %>.
    </p>
  </div>
</div>