config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :meetings
  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'welcome', to: 'welcome#index'

  get 'volunteers/propose', to: 'volunteers#propose'

  resources :volunteers, except: [:index, :edit]

  root to: 'pages#home'

  get 'volunteers/propose', to: 'volunteers#propose'

  get '/contact', to: 'pages#contact'

  get '/news', to: 'pages#news'

  get '/about', to: 'about#who'

  get '/quickstart', to: 'pages#quickstart'

  #about
  get '/about/conduct', to: 'about#conduct'

  get '/about/diversity', to: 'about#diversity'

  get '/about/press', to: 'about#press'

  get '/about/principals', to: 'about#principals'

  get '/about/projects', to: 'about#projects'

  # get '/about/vision', to: 'about#vision'

  get '/about/what', to: 'about#what'

  #get '/projects', to: 'projects#show', as: 'projects_show'

end

app/models/project.rb
class Project < ApplicationRecord
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  access all: [:show, :index], user: [:show, :index], site_admin: :all

  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :subtitle, :text, :img, :leadcontact, :github_url, :technical_lead, :content_lead, :proposal, :problem, :goal, :scope, :color, :trello, :slack)
    end
end

app/helpers/projects_helper.rb
  module ProjectsHelper
  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)

    options = {
      fenced_code_blocks: true,
      no_intra_emphasis: true,
      auto_link: true,
      lax_html_blocks: true,
      }

    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :project_title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle, id: :project_subtitle, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :color %>
    <%= form.color_field :color, id: :project_color, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :text %>
    <%= form.text_area :text, id: :project_text, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :img %>
    <%= form.text_area :img, id: :project_img, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :leadcontact %>
    <%= form.text_field :leadcontact, id: :project_leadcontact, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :github_url %>
    <%= form.text_field :github_url, id: :project_github_url, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :leadcontact %>
    <%= form.text_field :leadcontact, id: :project_leadcontact, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :technical_lead %>
    <%= form.text_field :technical_lead, id: :project_technical_lead, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :content_lead %>
    <%= form.text_field :content_lead, id: :project_content_lead, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :technical_lead %>
    <%= form.text_field :technical_lead, id: :project_technical_lead, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :problem %>
    <%= form.text_area :problem, id: :project_problem, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :proposal %>
    <%= form.text_area :proposal, id: :project_proposal, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :goal %>
    <%= form.text_area :goal, id: :project_goal, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :scope %>
    <%= form.text_area :scope, id: :project_scope, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :trello %>
    <%= form.text_area :trello, id: :project_trello, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :slack %>
    <%= form.text_area :slack, id: :project_slack, class: 'form-control' %>
  </div>


  <div class="actions">
    <%= form.submit "Submit", class: 'btn btn-primary btn-block' %>
  </div>

<% end %>

app/views/projects/edit.html.erb
<div class="container col-md-6 offset-md-3 topper">
  <div class="container">
    <h1>Editing project</h1>

    <%= render 'form', project: @project %>

    <%= link_to 'Discard edit', @project %> | <%= link_to 'Back to project home', projects_path %>
  </div>
</div>

app/views/projects/index.html.erb
<% colors = ["#221FE2","#17159e","#7a78ed"] %>
<svg width="100%" height="330" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg">
 <!-- Created with SVG-edit - https://github.com/SVG-Edit/svgedit-->
 <g class="layer">
  <title>Layer 1</title>
  <!-- <path d="m192.0325,274.13748l0,-1l1,1l-1,0z" fill="#9516bc" id="svg_25" stroke="#000000" stroke-dasharray="null" stroke-linecap="null" stroke-linejoin="null" stroke-width="0"/> -->
  <path d="m0,58l-0.5,177.5l3035,100l-1,-274l-633.5,-3.5z" fill=<%= colors[0] %> id="svg_1" stroke="#000000" stroke-dasharray="null" stroke-linecap="null" stroke-linejoin="null" stroke-width="0"/>
  <path d="m192.0325,274.13748l0,-1l1,1l-1,0z" fill="#5907f2" id="svg_25" stroke="#000000" stroke-dasharray="null" stroke-linecap="null" stroke-linejoin="null" stroke-width="0"/>
  <path d="m192.0325,274.13748l0,-1l1,1l-1,0z" fill="#5907f2" id="svg_25" stroke="#000000" stroke-dasharray="null" stroke-linecap="null" stroke-linejoin="null" stroke-width="0"/>
   <path d="m499.15255,197.45535l17.78572,-35.57143l47.42858,0l17.78572,35.57143l-17.78572,35.57144l-47.42858,0l-17.78572,-35.57144z" fill=<%= colors[2] %>   id="svg_6" stroke="#000000" stroke-dasharray="null" stroke-linecap="null" stroke-linejoin="null" stroke-width="0"/>
   <path d="m378.15255,76.45535l17.78572,-35.57143l47.42858,0l17.78572,35.57143l-17.78572,35.57144l-47.42858,0l-17.78572,-35.57144z" fill=<%= colors[1] %> id="svg_7" stroke="#000000" stroke-dasharray="null" stroke-linecap="null" stroke-linejoin="null" stroke-width="0"/>
   <path d="m440.15255,252.45535l17.78572,-35.57143l47.42858,0l17.78572,35.57143l-17.78572,35.57144l-47.42858,0l-17.78572,-35.57144z" fill=<%= colors[2] %> id="svg_8" stroke="#000000" stroke-dasharray="null" stroke-linecap="null" stroke-linejoin="null" stroke-width="0"/>
   <path d="m507.15255,293.45535l17.78572,-35.57143l47.42858,0l17.78572,35.57143l-17.78572,35.57144l-47.42858,0l-17.78572,-35.57144z" fill=<%= colors[1] %> id="svg_9" stroke="#000000" stroke-dasharray="null" stroke-linecap="null" stroke-linejoin="null" stroke-width="0"/>
   <path d="m299.15255,123.45535l17.78572,-35.57143l47.42858,0l17.78572,35.57143l-17.78572,35.57144l-47.42858,0l-17.78572,-35.57144z" fill=<%= colors[2] %> id="svg_10" stroke="#000000" stroke-dasharray="null" stroke-linecap="null" stroke-linejoin="null" stroke-width="0"/>
   <path d="m379.15255,162.45535l17.78572,-35.57143l47.42858,0l17.78572,35.57143l-17.78572,35.57144l-47.42858,0l-17.78572,-35.57144z" fill=<%= colors[1] %> id="svg_11" stroke="#000000" stroke-dasharray="null" stroke-linecap="null" stroke-linejoin="null" stroke-width="0"/>
   <path d="m447.15255,125.45535l17.78572,-35.57143l47.42858,0l17.78572,35.57143l-17.78572,35.57144l-47.42858,0l-17.78572,-35.57144z" fill=<%= colors[2] %> id="svg_12" stroke="#000000" stroke-dasharray="null" stroke-linecap="null" stroke-linejoin="null" stroke-width="0"/>
  <text xml:space="preserve" text-anchor="middle" font-family="Monospace" font-size="24" id="svg_72" y="170" x="70%" stroke-opacity="0" stroke-linecap="null" stroke-linejoin="null" stroke-dasharray="null" stroke-width="0" stroke="#000000" fill="#f9f4f4">Current Projects</text>
 </g>
</svg>

<div class="container col-md-12 topper">
  <div class="container">
    <p id="notice"><%= notice %></p>
  </div>
<div class="row">
    <% @projects.each do |project| %>
      <div class="col-md-3" style="margin-left: 20px">
          <%= link_to "projects/#{project.id}" do %>
            <%= image_tag project.img, alt: project.title %>
        </div>
          <% end %>

    <% end %>
  </div>
</div>

    <% if @projects.count >= 4 %>
    <div id="next-three-blogposts" class="row featurette topper">
      <% 3.times do |i| %>
        <% count = @count - 2 - i %>
        <div class="col-lg">
          <%= link_to "/projects/#{@projects[count].id}" do %>
            <%= image_tag @projects[count].img, alt: @projects[count].title, class:"img-fluid mx-auto blog-post-img"  %>
            <h4 class="headline"><%= @projects[count].title %></h4>
            <h6 class="lede"><%= @projects[count].subtitle %></h6>
            <p>
              <span class="lede author">
                <% if @projects[count].updated_at > @projects[count].created_at %>
                  Updated <%= @projects[count].updated_at.to_s[5,5] %>
                <% else %>
                  <%= @projects[count].created_at.to_s[5,5] %>
                <% end %>
              </span>
            </p>
          <% end %>
        </div>
      <% end %>
    </div>
    <% end %>

    <% if @projects.count >= 7 %>
    <div id="next-three-blogposts" class="row featurette">
      <% 3.times do |i| %>
        <% count = @count - 5 - i %>
        <div class="col-lg">
          <%= link_to "/projects/#{@projects[count].id}" do %>
            <%= image_tag @projects[count].img, alt: @projects[count].title, class:"img-fluid mx-auto blog-post-img"  %>
            <h4 class="headline"><%= @projects[count].title %></h4>
            <h6 class="lede"><%= @projects[count].subtitle %></h6>
            <p>
              <span class="lede author">
                <% if @projects[count].updated_at > @projects[count].created_at %>
                  Updated <%= @projects[count].updated_at.to_s[5,5] %>
                <% else %>
                  <%= @projects[count].created_at.to_s[5,5] %>
                <% end %>
              </span>
            </p>
          <% end %>
        </div>
      <% end %>
    </div>
    <% end %>
  </div>

  <hr class="featurette-divider">

  <div class="container">
    <%= link_to 'New project', new_project_path if logged_in?(:site_admin) %>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container col-md-6 offset-md-3 topper">project
  <div class="container">
    <%= render 'form', project: @project %>

    <%= link_to 'Back', projects_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/projects/show.html.erb
<% case @project.color %>
<% when "#5907f2" %>
<% colors = ["#5907f2","#d098e2","#570472"] %>
<% when "#269b0f" %>
<% colors = ["#269b0f","#67b957","#1a6c0a"] %>
<% when "#e2841f" %>
<% colors = ["#e2841f","#eaa862","#b46918"] %>
<% else %>
<% colors = ["#5907f2","#d098e2","#570472"] %>
<% end %>
<style>


</style>
<svg width="100%" height="330" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg">
 <!-- Created with SVG-edit - https://github.com/SVG-Edit/svgedit-->
 <g class="layer">
  <title>Layer 1</title>
  <!-- <path d="m192.0325,274.13748l0,-1l1,1l-1,0z" fill="#9516bc" id="svg_25" stroke="#000000" stroke-dasharray="null" stroke-linecap="null" stroke-linejoin="null" stroke-width="0"/> -->
  <path d="m0,58l-0.5,177.5l3035,100l-1,-274l-633.5,-3.5z" fill=<%= colors[0] %> id="svg_1" stroke="#000000" stroke-dasharray="null" stroke-linecap="null" stroke-linejoin="null" stroke-width="0"/>
  <path d="m192.0325,274.13748l0,-1l1,1l-1,0z" fill="#5907f2" id="svg_25" stroke="#000000" stroke-dasharray="null" stroke-linecap="null" stroke-linejoin="null" stroke-width="0"/>
  <path d="m192.0325,274.13748l0,-1l1,1l-1,0z" fill="#5907f2" id="svg_25" stroke="#000000" stroke-dasharray="null" stroke-linecap="null" stroke-linejoin="null" stroke-width="0"/>
   <path d="m499.15255,197.45535l17.78572,-35.57143l47.42858,0l17.78572,35.57143l-17.78572,35.57144l-47.42858,0l-17.78572,-35.57144z" fill=<%= colors[2] %>   id="svg_6" stroke="#000000" stroke-dasharray="null" stroke-linecap="null" stroke-linejoin="null" stroke-width="0"/>
   <path d="m378.15255,76.45535l17.78572,-35.57143l47.42858,0l17.78572,35.57143l-17.78572,35.57144l-47.42858,0l-17.78572,-35.57144z" fill=<%= colors[1] %> id="svg_7" stroke="#000000" stroke-dasharray="null" stroke-linecap="null" stroke-linejoin="null" stroke-width="0"/>
   <path d="m440.15255,252.45535l17.78572,-35.57143l47.42858,0l17.78572,35.57143l-17.78572,35.57144l-47.42858,0l-17.78572,-35.57144z" fill=<%= colors[2] %> id="svg_8" stroke="#000000" stroke-dasharray="null" stroke-linecap="null" stroke-linejoin="null" stroke-width="0"/>
   <path d="m507.15255,293.45535l17.78572,-35.57143l47.42858,0l17.78572,35.57143l-17.78572,35.57144l-47.42858,0l-17.78572,-35.57144z" fill=<%= colors[1] %> id="svg_9" stroke="#000000" stroke-dasharray="null" stroke-linecap="null" stroke-linejoin="null" stroke-width="0"/>
   <path d="m299.15255,123.45535l17.78572,-35.57143l47.42858,0l17.78572,35.57143l-17.78572,35.57144l-47.42858,0l-17.78572,-35.57144z" fill=<%= colors[2] %> id="svg_10" stroke="#000000" stroke-dasharray="null" stroke-linecap="null" stroke-linejoin="null" stroke-width="0"/>
   <path d="m379.15255,162.45535l17.78572,-35.57143l47.42858,0l17.78572,35.57143l-17.78572,35.57144l-47.42858,0l-17.78572,-35.57144z" fill=<%= colors[1] %> id="svg_11" stroke="#000000" stroke-dasharray="null" stroke-linecap="null" stroke-linejoin="null" stroke-width="0"/>
   <path d="m447.15255,125.45535l17.78572,-35.57143l47.42858,0l17.78572,35.57143l-17.78572,35.57144l-47.42858,0l-17.78572,-35.57144z" fill=<%= colors[2] %> id="svg_12" stroke="#000000" stroke-dasharray="null" stroke-linecap="null" stroke-linejoin="null" stroke-width="0"/>
  <text xml:space="preserve" text-anchor="middle" font-family="Monospace" font-size="24" id="svg_72" y="170" x="70%" stroke-opacity="0" stroke-linecap="null" stroke-linejoin="null" stroke-dasharray="null" stroke-width="0" stroke="#000000" fill="#f9f4f4"><%= @project.title%></text>
 </g>
</svg>
</div>
<div class="container">
  <div class="row">

    <div class="col-lg-6">
      <div style="padding: 20px; margin: 10px">
        <h5 style="color: <%= colors[2] %>"> <strong> Contact: </strong></h5>
        <p class="blog-text"><%= markdown @project.content_lead %> </p>
        <h5 style="color: <%= colors[2] %>"><strong> Problem: </strong></h5>
        <p class="blog-text" style="color: black;"><%= markdown @project.problem %></p>
        <h5 style="color: <%= colors[2] %>"><strong> Scope: </strong></h5>
        <p class="blog-text" style="color: black;"><%= markdown @project.scope %></p>
        <h5 style="color: <%= colors[2] %>"><strong> Proposal: </strong></h5>
        <p><%= markdown @project.proposal %></p>
      </div>
    </div>

<div class="col-lg-5" style="text-align: right; margin-right: 10px; background: <%= colors[0] %>">
  <br>
  <%= link_to 'Get Involved!', new_volunteer_path, class: "btn btn-block", style: "background: #{colors[2]}" %>

  <%= link_to "#{@project.github_url}/wiki" do %>
  <i class="fab fa-wikipedia-w text_color text-right" style="font-size: 300%; margin: 10px; color: <%= colors[1] %> "> </i>
  <% end %>
  <%= link_to @project.github_url do %>
  <i class="fab fa-github text_color text-right" style="font-size: 300%; margin: 10px; color: <%= colors[1] %>"> </i>
  <% end %>
  <%= link_to @project.slack do %>
  <i class="fab fa-slack text_color text-right" style="font-size: 300%; margin: 10px; color: <%= colors[1] %>"> </i>
  <% end %>
  <% if @project.trello? %>
    <%= link_to @project.trello do %>
      <i class="fab fa-trello text_color text-right" style="font-size: 300%; margin: 10px; color: <%= colors[1] %>"> </i>
    <% end %>
  <% end %>
  <%= image_tag @project.img %>

  <div style="text-align: left; margin-left: 10%;">
      <%= link_to 'Edit', edit_project_path(@project), class: "btn", style: "background: #{colors[2]}"   if logged_in?(:site_admin) %>
      <%= link_to 'Delete', project_path(@project), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn",style: "background: #{colors[2]}"   if logged_in?(:site_admin) %>
  </div>

</div>


  </div>
</div>
<!--
<div class="col-lg-12 topper row">
    <div class="text-right">
      <%= link_to @project.github_url do %>
      <i class="fab fa-github text_color text-right" style="font-size: 300%;"> </i>
      <% end %>
      <%= link_to @project.slack do %>
      <i class="fab fa-slack text_color text-right" style="font-size: 300%;"> </i>
      <% end %>
      <% if @project.trello? %>
        <%= link_to @project.trello do %>
          <i class="fab fa-trello text_color text-right" style="font-size: 300%;"> </i>
        <% end %>
      <% end %>
    </div>
  </div>

<div style:"margin: 10 auto">
    <h5 class="text_color"> <strong> Contact: </strong></h5>
    <p class="blog-text"><%= @project.content_lead %> </p>
    <h5 class="text_color"><strong> Problem: </strong></h5>
    <p class="blog-text"><%= @project.problem %></p>

    <h5 class="text_color"><strong> Scope: </strong></h5>
    <p class="blog-text"><%= @project.scope %></p>
    <h5 class="text_color"><strong> Goal: </strong></h5>
    <p class="blog-text"><%= @project.goal %></p>
    <h5 class="text_color"><strong> Proposal: </strong></h5>
    <p class="blog-text"><%= @project.proposal %></p>
</div>

    <div class="row ">
      <div class="col-md-3 text-center">
        <%= link_to 'Get involved!', new_volunteer_path, class: "btn btn-primary btn-block", size: "30x100", style:"background: colors[2]" %>
      </div>
      <div class="col-md-3 text-center">
        <%= link_to 'Back', root_path, class: "btn btn-primary btn-block", size: "30x100" %>
      </div>
      <div class="col" style="text-align:right">
        <%= link_to 'Edit', edit_project_path(@project), class: "btn btn-primary"  if logged_in?(:site_admin) %>
        <%= link_to 'Delete', project_path(@project), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary"  if logged_in?(:site_admin) %>
      </div>
    </div>
</div> -->